// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "./sidebar"
import "./grayscale"
import "./accesibilidad"
import "./resaltado"
import "./tamaño"
import "./lectorvoz"
import "./animaciones"
import "./dropdown"
import "./calendario"